version: '2'

services:

  elasticsearch:
    build: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ~/elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      VIRTUAL_HOST: "elastic.micab.co"
    networks:
      - elk
    restart: unless-stopped
    logging:
      options:
        max-size: "1mb"
        max-file: "10"
  logstash:
    build: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch
    restart: unless-stopped
    logging:
      options:
        max-size: "1mb"
        max-file: "10"
  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    environment:
      VIRTUAL_HOST: "kibana.micab.co"
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
    restart: unless-stopped
    logging:
      options:
        max-size: "1mb"
        max-file: "10"
networks:

  elk:
    driver: bridge
